"""Add growth rate to household services scenario

Revision ID: 0928827c26bf
Revises: b4948fbf8df4
Create Date: 2025-02-13 09:34:09.445617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0928827c26bf'
down_revision = 'b4948fbf8df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_services_scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growth_rate', sa.Numeric(precision=10, scale=4), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_services_scenario', schema=None) as batch_op:
        batch_op.drop_column('growth_rate')

    # ### end Alembic commands ###
