"""Add household services model

Revision ID: 1130e9f5a8c0
Revises: a1f71379b472
Create Date: 2025-02-13 07:59:57.954507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1130e9f5a8c0'
down_revision = 'a1f71379b472'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_services_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluee_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('annual_hours', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('wage_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('growth_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('projection_years', sa.Integer(), nullable=False),
    sa.Column('present_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluee_id'], ['evaluee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('household_services_scenario')
    # ### end Alembic commands ###
