"""Add offset wages model

Revision ID: 555beb676203
Revises: be76d8f078b5
Create Date: 2025-02-09 18:01:51.606364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555beb676203'
down_revision = 'be76d8f078b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offset_wage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['earnings_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offset_wage')
    # ### end Alembic commands ###
