"""Add healthcare models

Revision ID: 61729dbdba53
Revises: 555beb676203
Create Date: 2025-02-10 14:29:08.800506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61729dbdba53'
down_revision = '555beb676203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluee_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('growth_method', sa.String(length=20), nullable=True),
    sa.Column('growth_rate_custom', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('discount_method', sa.String(length=20), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('partial_offset', sa.Boolean(), nullable=True),
    sa.Column('total_offset', sa.Boolean(), nullable=True),
    sa.Column('projection_years', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluee_id'], ['evaluee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medical_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('annual_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['healthcare_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_item')
    op.drop_table('healthcare_scenario')
    # ### end Alembic commands ###
