"""add_one_time_and_duration_to_medical_items

Revision ID: 8d7ccb08826d
Revises: 0928827c26bf
Create Date: 2025-02-14 13:34:18.422910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7ccb08826d'
down_revision = '0928827c26bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_one_time', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('start_year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duration_years', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_item', schema=None) as batch_op:
        batch_op.drop_column('duration_years')
        batch_op.drop_column('start_year')
        batch_op.drop_column('is_one_time')

    # ### end Alembic commands ###
