"""Add fringe benefits models

Revision ID: 98a5d78a0d9b
Revises: e83b3d01bdbd
Create Date: 2025-02-19 09:37:29.084498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a5d78a0d9b'
down_revision = 'e83b3d01bdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecec_geographic_region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('wages_and_salaries', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_benefits', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('region')
    )
    op.create_table('ecec_worker_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_type', sa.String(length=100), nullable=False),
    sa.Column('wages_and_salaries', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_benefits', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('legally_required_benefits', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_type')
    )
    op.create_table('fringe_benefit_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluee_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('worker_type', sa.String(length=100), nullable=False),
    sa.Column('annual_salary', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('inflation_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('years_since_update', sa.Integer(), nullable=True),
    sa.Column('adjusted_fringe_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fringe_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_compensation', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluee_id'], ['evaluee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fringe_benefit_scenario')
    op.drop_table('ecec_worker_type')
    op.drop_table('ecec_geographic_region')
    # ### end Alembic commands ###
