"""Add interval_years to medical_item table

Revision ID: a9727fa33771
Revises: 8f3dcaac6232
Create Date: 2025-02-24 11:58:20.191546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9727fa33771'
down_revision = '8f3dcaac6232'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interval_years', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_item', schema=None) as batch_op:
        batch_op.drop_column('interval_years')
    # ### end Alembic commands ###
