"""Add new columns to household services scenario

Revision ID: b4948fbf8df4
Revises: 1130e9f5a8c0
Create Date: 2025-02-13 09:30:29.838791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4948fbf8df4'
down_revision = '1130e9f5a8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pension_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluee_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('calculation_method', sa.String(length=20), nullable=False),
    sa.Column('growth_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('present_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('years_to_retirement', sa.Integer(), nullable=True),
    sa.Column('annual_contribution', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('retirement_age', sa.Integer(), nullable=True),
    sa.Column('life_expectancy', sa.Integer(), nullable=True),
    sa.Column('annual_pension_benefit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['evaluee_id'], ['evaluee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_service_stage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('stage_number', sa.Integer(), nullable=False),
    sa.Column('years', sa.Integer(), nullable=False),
    sa.Column('annual_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['household_services_scenario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('household_services_scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('area_wage_adjustment', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('reduction_percentage', sa.Numeric(precision=10, scale=4), nullable=False))
        batch_op.drop_column('annual_hours')
        batch_op.drop_column('growth_rate')
        batch_op.drop_column('wage_rate')
        batch_op.drop_column('projection_years')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('household_services_scenario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('projection_years', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('wage_rate', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('growth_rate', sa.NUMERIC(precision=10, scale=4), nullable=False))
        batch_op.add_column(sa.Column('annual_hours', sa.NUMERIC(precision=10, scale=2), nullable=False))
        batch_op.drop_column('reduction_percentage')
        batch_op.drop_column('area_wage_adjustment')

    op.drop_table('household_service_stage')
    op.drop_table('pension_scenario')
    # ### end Alembic commands ###
