"""Initial migration

Revision ID: be76d8f078b5
Revises: 
Create Date: 2025-02-07 11:17:37.195058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be76d8f078b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('uses_discounting', sa.Boolean(), nullable=True),
    sa.Column('discount_rates', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('date_of_injury', sa.DateTime(), nullable=True),
    sa.Column('life_expectancy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('work_life_expectancy', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('years_to_final_separation', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('worklife_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('gross_earnings_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('worklife_adjustment', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('unemployment_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fringe_benefit', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('tax_liability', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('wrongful_death', sa.Boolean(), nullable=True),
    sa.Column('personal_type', sa.String(length=50), nullable=True),
    sa.Column('personal_percentage', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluee_id', sa.Integer(), nullable=False),
    sa.Column('scenario_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('wage_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('residual_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('growth_rate', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('adjustment_factor', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('present_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('total_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['evaluee_id'], ['evaluee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('earnings_scenario')
    op.drop_table('evaluee')
    # ### end Alembic commands ###
