"""add_growth_rate_and_age_ranges_to_medical_items

Revision ID: d62011859c42
Revises: 8d7ccb08826d
Create Date: 2025-02-14 13:40:02.922769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd62011859c42'
down_revision = '8d7ccb08826d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('growth_rate', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('age_initiated', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('age_through', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_item', schema=None) as batch_op:
        batch_op.drop_column('age_through')
        batch_op.drop_column('age_initiated')
        batch_op.drop_column('growth_rate')

    # ### end Alembic commands ###
